/*
 * Copyright (C) 2014-2017 team-cachebox.de
 *
 * Licensed under the : GNU General Public License (GPL);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/gpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.longri.cachebox3.settings;

import de.longri.cachebox3.CB;
import de.longri.cachebox3.settings.types.Audio;
import de.longri.cachebox3.settings.types.SettingBool;
import de.longri.cachebox3.settings.types.SettingCategory;
import de.longri.cachebox3.settings.types.SettingColor;
import de.longri.cachebox3.settings.types.SettingDouble;
import de.longri.cachebox3.settings.types.SettingEncryptedString;
import de.longri.cachebox3.settings.types.SettingFile;
import de.longri.cachebox3.settings.types.SettingFloat;
import de.longri.cachebox3.settings.types.SettingFolder;
import de.longri.cachebox3.settings.types.SettingInt;
import de.longri.cachebox3.settings.types.SettingIntArray;
import de.longri.cachebox3.settings.types.SettingLongString;
import de.longri.cachebox3.settings.types.SettingStoreType;
import de.longri.cachebox3.settings.types.SettingString;
import de.longri.cachebox3.settings.types.SettingStringArray;
import de.longri.cachebox3.settings.types.SettingStringList;
import de.longri.cachebox3.settings.types.SettingTime;
import de.longri.cachebox3.settings.types.SettingUsage;
import de.longri.cachebox3.settings.types.SettingsAudio;
import de.longri.cachebox3.settings.types.SettingsList;
import de.longri.cachebox3.utils.HSV_Color;

/**
 * Created by Longri on 31.07.16.
 */
public class Settings extends Settings_Skin {

    static {
        new de.longri.cachebox3.settings.types.SettingsList();
    }


    public static final de.longri.cachebox3.settings.types.SettingString GcLogin = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("GcLogin", de.longri.cachebox3.settings.types.SettingCategory.Login, NORMAL, "", de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingEncryptedString GcAPI = (de.longri.cachebox3.settings.types.SettingEncryptedString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingEncryptedString("GcAPI", de.longri.cachebox3.settings.types.SettingCategory.Login, DEVELOPER, "", de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingEncryptedString GcAPIStaging = (de.longri.cachebox3.settings.types.SettingEncryptedString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingEncryptedString("GcAPIStaging", de.longri.cachebox3.settings.types.SettingCategory.Login, DEVELOPER, "", de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));

    // Folder Settings
    public static final de.longri.cachebox3.settings.types.SettingFolder DescriptionImageFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("DescriptionImageFolder", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, CB.WorkPath + "/repository/images", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingFolder DescriptionImageFolderLocal = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("DescriptionImageFolderLocal", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingFolder SpoilerFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("SpoilerFolder", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, CB.WorkPath + "/repository/spoilers", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingFolder SpoilerFolderLocal = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("SpoilerFolderLocal", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingFolder PocketQueryFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("PocketQueryFolder", de.longri.cachebox3.settings.types.SettingCategory.Folder, DEVELOPER, CB.WorkPath + "/pocketQuery", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingFolder UserImageFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("UserImageFolder", de.longri.cachebox3.settings.types.SettingCategory.Folder, NORMAL, CB.WorkPath + "/user/media", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingBool StagingAPI = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("StagingAPI", de.longri.cachebox3.settings.types.SettingCategory.Folder, DEVELOPER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL));

    public static final de.longri.cachebox3.settings.types.SettingInt conection_timeout = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("conection_timeout", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, 10000, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingInt socket_timeout = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("socket_timeout", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, 60000, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingEncryptedString GcVotePassword = (de.longri.cachebox3.settings.types.SettingEncryptedString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingEncryptedString("GcVotePassword", de.longri.cachebox3.settings.types.SettingCategory.Login, NORMAL, "", de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingDouble ParkingLatitude = (de.longri.cachebox3.settings.types.SettingDouble) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingDouble("ParkingLatitude", de.longri.cachebox3.settings.types.SettingCategory.Positions, NEVER, 0, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingDouble ParkingLongitude = (de.longri.cachebox3.settings.types.SettingDouble) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingDouble("ParkingLongitude", de.longri.cachebox3.settings.types.SettingCategory.Positions, NEVER, 0, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool FieldNotesLoadAll = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("FieldNotesLoadAll", de.longri.cachebox3.settings.types.SettingCategory.Fieldnotes, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt FieldNotesLoadLength = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("FieldNotesLoadLength", de.longri.cachebox3.settings.types.SettingCategory.Fieldnotes, EXPERT, 10, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString Friends = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("Friends", de.longri.cachebox3.settings.types.SettingCategory.Login, NORMAL, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ShowAllWaypoints = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ShowAllWaypoints", de.longri.cachebox3.settings.types.SettingCategory.Map, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool DisableLiveMap = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("DisableLiveMap", de.longri.cachebox3.settings.types.SettingCategory.LiveMap, NORMAL, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt LiveMaxCount = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("LiveMaxCount", de.longri.cachebox3.settings.types.SettingCategory.LiveMap, EXPERT, 350, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool LiveExcludeFounds = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("LiveExcludeFounds", de.longri.cachebox3.settings.types.SettingCategory.LiveMap, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool LiveExcludeOwn = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("LiveExcludeOwn", de.longri.cachebox3.settings.types.SettingCategory.LiveMap, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingBool DirectOnlineLog = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("DirectOnlineLog", de.longri.cachebox3.settings.types.SettingCategory.Fieldnotes, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool showSandbox = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("showSandbox", de.longri.cachebox3.settings.types.SettingCategory.RememberAsk, NORMAL, false, de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool showGestureHelp = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("showGestureHelp", de.longri.cachebox3.settings.types.SettingCategory.RememberAsk, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ACB));


    // Settings Compass
    public static final de.longri.cachebox3.settings.types.SettingInt HardwareCompassLevel = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("HardwareCompassLevel", de.longri.cachebox3.settings.types.SettingCategory.Gps, NORMAL, 5, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool HardwareCompass = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("HardwareCompass", de.longri.cachebox3.settings.types.SettingCategory.Gps, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt gpsUpdateTime = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("gpsUpdateTime", de.longri.cachebox3.settings.types.SettingCategory.Gps, NORMAL, 500, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowMap = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowMap", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowWP_Name = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowWP_Name", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowWP_Icon = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowWP_Icon", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowAttributes = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowAttributes", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowGcCode = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowGcCode", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowCoords = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowCoords", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowWpDesc = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowWpDesc", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowSatInfos = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowSatInfos", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowSunMoon = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowSunMoon", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowTargetDirection = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowTargetDirection", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowSDT = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowSDT", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassShowLastFound = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassShowLastFound", de.longri.cachebox3.settings.types.SettingCategory.Compass, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString OverrideUrl = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("OverrideUrl", de.longri.cachebox3.settings.types.SettingCategory.Login, DEVELOPER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    // Folder
    public static final de.longri.cachebox3.settings.types.SettingFolder TrackFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("TrackFolder", de.longri.cachebox3.settings.types.SettingCategory.Folder, EXPERT, CB.WorkPath + "/user/tracks", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, true));
    // Files
    public static final de.longri.cachebox3.settings.types.SettingFile DatabaseName = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFile("DatabaseName", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, CB.WorkPath + "/cachebox.db3", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, "db3"));
    public static final de.longri.cachebox3.settings.types.SettingFile FieldNotesGarminPath = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFile("FieldNotesGarminPath", de.longri.cachebox3.settings.types.SettingCategory.Folder, DEVELOPER, CB.WorkPath + "/user/geocache_visits.txt", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingFile gpxExportFileName = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFile("gpxExportFileName", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, CB.WorkPath + "/user/export.gpx", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, "gpx"));
    //
    public static final de.longri.cachebox3.settings.types.SettingBool MapShowRating = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MapShowRating", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool MapShowDT = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MapShowDT", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool MapShowTitles = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MapShowTitles", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool TrackRecorderStartup = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("TrackRecorderStartup", de.longri.cachebox3.settings.types.SettingCategory.Misc, NORMAL, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool MapShowCompass = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MapShowCompass", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompassNorthOriented = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompassNorthOriented", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool MapNorthOriented = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MapNorthOriented", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ImportGpx = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ImportGpx", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CacheMapData = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CacheMapData", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CacheImageData = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CacheImageData", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CacheSpoilerData = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CacheSpoilerData", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool SuppressPowerSaving = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("SuppressPowerSaving", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool GCAdditionalImageDownload = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("GCAdditionalImageDownload", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool StartWithAutoSelect = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("StartWithAutoSelect", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool FieldnotesUploadAll = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("FieldnotesUploadAll", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool MultiDBAsk = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MultiDBAsk", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool SearchWithoutFounds = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("SearchWithoutFounds", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool SearchWithoutOwns = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("SearchWithoutOwns", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool SearchOnlyAvailable = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("SearchOnlyAvailable", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool quickButtonShow = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("quickButtonShow", de.longri.cachebox3.settings.types.SettingCategory.QuickList, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool DescriptionNoAttributes = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("DescriptionNoAttributes", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool quickButtonLastShow = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("quickButtonLastShow", de.longri.cachebox3.settings.types.SettingCategory.QuickList, DEVELOPER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool newInstall = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("newInstall", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ImperialUnits = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ImperialUnits", de.longri.cachebox3.settings.types.SettingCategory.Misc, NORMAL, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ShowDirektLine = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ShowDirektLine", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ImportRatings = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ImportRatings", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ImportPQsFromGeocachingCom = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ImportPQsFromGeocachingCom", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool switchViewApproach = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("switchViewApproach", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool hasCallPermission = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("hasCallPermission", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool vibrateFeedback = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("vibrateFeedback", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool hasPQ_PlugIn = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("hasPQ_PlugIn", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool hasFTF_PlugIn = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("hasFTF_PlugIn", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool dynamicZoom = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("dynamicZoom", de.longri.cachebox3.settings.types.SettingCategory.CarMode, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool dynamicFilterAtSearch = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("dynamicFilterAtSearch", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool DeleteLogs = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("DeleteLogs", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool CompactDB = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("CompactDB", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool AskAgain = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("AskAgain", de.longri.cachebox3.settings.types.SettingCategory.RememberAsk, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingBool RememberAsk_Get_API_Key = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("RememberAsk_Get_API_Key", de.longri.cachebox3.settings.types.SettingCategory.RememberAsk, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool Ask_Switch_GPS_ON = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("Ask_Switch_GPS_ON", de.longri.cachebox3.settings.types.SettingCategory.RememberAsk, NORMAL, true, de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingBool TB_DirectLog = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("TB_DirectLog", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingBool MapHideMyFinds = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MapHideMyFinds", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    // int
    public static final de.longri.cachebox3.settings.types.SettingInt LogMaxMonthAge = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("LogMaxMonthAge", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, 6, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt LogMinCount = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("LogMinCount", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, 99999, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt installRev = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("installRev", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, 0, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt MapIniWidth = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("MapIniWidth", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, 480, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt MapIniHeight = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("MapIniHeight", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, 535, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt VibrateTime = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("VibrateTime", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, 20, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt FoundOffset = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("FoundOffset", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, 0, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt MultiDBAutoStartTime = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("MultiDBAutoStartTime", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, 0, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt lastSearchRadius = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("lastSearchRadius", de.longri.cachebox3.settings.types.SettingCategory.API, NEVER, 5, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt LastMapToggleBtnState = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("LastMapToggleBtnState", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, 0, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt dynamicZoomLevelMax = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("dynamicZoomLevelMax", de.longri.cachebox3.settings.types.SettingCategory.CarMode, NORMAL, 17, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt dynamicZoomLevelMin = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("dynamicZoomLevelMin", de.longri.cachebox3.settings.types.SettingCategory.CarMode, NORMAL, 15, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    // String
    public static final de.longri.cachebox3.settings.types.SettingString LastSelectedCache = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("LastSelectedCache", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingString CacheHistory = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("CacheHistory", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingString NavigationProvider = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList
            .addSetting(new de.longri.cachebox3.settings.types.SettingString("NavigationProvider", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, "http://openls.geog.uni-heidelberg.de/testing2015/route?", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString FoundTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("FoundTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, FOUND, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString AttendedTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("AttendedTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, ATTENDED, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString WebcamTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("WebCamTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, WEBCAM, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString DNFTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("DNFTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, DNF, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString NeedsMaintenanceTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("NeedsMaintenanceTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, LOG, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString AddNoteTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("AddNoteTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, LOG, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString DiscoverdTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("DiscoverdTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, DISCOVERD, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString VisitedTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("VisitedTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, VISITED, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString DroppedTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("DroppedTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, DROPPED, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString GrabbedTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("GrabbedTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, GRABED, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString PickedTemplate = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("PickedTemplate", de.longri.cachebox3.settings.types.SettingCategory.Templates, NORMAL, PICKED, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString SpoilersDescriptionTags = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("SpoilersDescriptionTags", de.longri.cachebox3.settings.types.SettingCategory.Internal, DEVELOPER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString quickButtonList = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("quickButtonList", de.longri.cachebox3.settings.types.SettingCategory.QuickList, DEVELOPER, "5,0,1,3,2", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString GcJoker = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("GcJoker", de.longri.cachebox3.settings.types.SettingCategory.Login, NORMAL, "", de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingStringArray Navis = (de.longri.cachebox3.settings.types.SettingStringArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingStringArray("Navis", de.longri.cachebox3.settings.types.SettingCategory.Misc, NORMAL, "Google", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, navis));

    // ArrayInt
    public static final de.longri.cachebox3.settings.types.SettingIntArray ZoomCross = (de.longri.cachebox3.settings.types.SettingIntArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingIntArray("ZoomCross", de.longri.cachebox3.settings.types.SettingCategory.Map, NORMAL, 16, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, CrossLevel));
    public static final de.longri.cachebox3.settings.types.SettingIntArray SoundApproachDistance = (de.longri.cachebox3.settings.types.SettingIntArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingIntArray("SoundApproachDistance", de.longri.cachebox3.settings.types.SettingCategory.Misc, NORMAL, 50, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, approach));
    public static final de.longri.cachebox3.settings.types.SettingIntArray TrackDistance = (de.longri.cachebox3.settings.types.SettingIntArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingIntArray("TrackDistance", de.longri.cachebox3.settings.types.SettingCategory.Misc, NORMAL, 3, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, TrackDistanceArray));

    // double

    // longString
    //	public static final SettingLongString Filter = (SettingLongString) SettingsList.addSetting(new SettingLongString("Filter", SettingCategory.Misc, NEVER, FilterProperties.presets[0].toString(), SettingStoreType.Local, SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingLongString FilterNew = (de.longri.cachebox3.settings.types.SettingLongString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("FilterNew", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ALL));
    public static final de.longri.cachebox3.settings.types.SettingLongString UserFilter = (de.longri.cachebox3.settings.types.SettingLongString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingLongString("UserFilter", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingLongString UserFilterNew = (de.longri.cachebox3.settings.types.SettingLongString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingLongString("UserFilterNew", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingTime ScreenLock = (de.longri.cachebox3.settings.types.SettingTime) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingTime("ScreenLock", de.longri.cachebox3.settings.types.SettingCategory.Misc, NEVER, 60000, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    // AudioSettings

    public static final de.longri.cachebox3.settings.types.SettingsAudio Approach = (de.longri.cachebox3.settings.types.SettingsAudio) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingsAudio("Approach", de.longri.cachebox3.settings.types.SettingCategory.Sounds, EXPERT, new de.longri.cachebox3.settings.types.Audio("data/sound/Approach.ogg", false, false, 1.0f), de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingsAudio GPS_lose = (de.longri.cachebox3.settings.types.SettingsAudio) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingsAudio("GPS_lose", de.longri.cachebox3.settings.types.SettingCategory.Sounds, EXPERT, new de.longri.cachebox3.settings.types.Audio("data/sound/GPS_lose.ogg", false, false, 1.0f), de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingsAudio GPS_fix = (de.longri.cachebox3.settings.types.SettingsAudio) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingsAudio("GPS_fix", de.longri.cachebox3.settings.types.SettingCategory.Sounds, EXPERT, new de.longri.cachebox3.settings.types.Audio("data/sound/GPS_Fix.ogg", false, false, 1.0f), de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingsAudio AutoResortSound = (de.longri.cachebox3.settings.types.SettingsAudio) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingsAudio("AutoResortSound", de.longri.cachebox3.settings.types.SettingCategory.Sounds, EXPERT, new de.longri.cachebox3.settings.types.Audio("data/sound/AutoResort.ogg", false, false, 1.0f), de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ShowFieldnotesCMwithFirstShow = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ShowFieldnotesCMwithFirstShow", de.longri.cachebox3.settings.types.SettingCategory.Fieldnotes, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ShowFieldnotesAsDefaultView = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ShowFieldnotesAsDefaultView", de.longri.cachebox3.settings.types.SettingCategory.Fieldnotes, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool LiveMapEnabeld = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("LiveMapEnabeld", de.longri.cachebox3.settings.types.SettingCategory.LiveMap, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingBool AppRaterDontShowAgain = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("AppRaterDontShowAgain", de.longri.cachebox3.settings.types.SettingCategory.RememberAsk, NORMAL, false, de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingInt AppRaterlaunchCount = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("AppRaterlaunchCount", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, 0, de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString AppRaterFirstLunch = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingString("AppRaterFirstLunch", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, "0", de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingBool nightMode = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("nightMode", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));


    public static final de.longri.cachebox3.settings.types.SettingDouble MapViewFontFaktor = (de.longri.cachebox3.settings.types.SettingDouble) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingDouble("MapViewFontFaktor", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, 1.0, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingInt LongClicktime = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("LongClicktime", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, 600, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingsAudio GlobalVolume = (de.longri.cachebox3.settings.types.SettingsAudio) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingsAudio("GlobalVolume", de.longri.cachebox3.settings.types.SettingCategory.Sounds, NORMAL, new Audio("data/sound/Approach.ogg", false, false, 1.0f), de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingFloat MapViewDPIFaktor = (de.longri.cachebox3.settings.types.SettingFloat) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingFloat("MapViewDPIFaktor", de.longri.cachebox3.settings.types.SettingCategory.Map, EXPERT, CB.getScalefactor(), de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    // überprüfen
    public static final de.longri.cachebox3.settings.types.SettingFolder ImageCacheFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("ImageCacheFolder", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, CB.WorkPath + "/repository/cache", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ACB, true));

    public static final de.longri.cachebox3.settings.types.SettingBool GestureOn = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("GestureOn", de.longri.cachebox3.settings.types.SettingCategory.Misc, EXPERT, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingColor LiveMapBackgroundColor = (de.longri.cachebox3.settings.types.SettingColor) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingColor("LiveMapBackgroundColor", de.longri.cachebox3.settings.types.SettingCategory.LiveMap, NORMAL, new HSV_Color(0.8f, 0.8f, 1f, 1f), de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));


    public static final de.longri.cachebox3.settings.types.SettingBool SettingsShowExpert = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("SettingsShowExpert", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool SettingsShowAll = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("SettingsShowAll", de.longri.cachebox3.settings.types.SettingCategory.Internal, NEVER, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingFile Sel_LanguagePath = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFile("Sel_LanguagePath", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, "lang/en-GB/strings.ini", de.longri.cachebox3.settings.types.SettingStoreType.Platform, de.longri.cachebox3.settings.types.SettingUsage.ALL, "lan"));
    public static final de.longri.cachebox3.settings.types.SettingFolder LanguagePath = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("LanguagePath", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, "lang", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));


    public static final de.longri.cachebox3.settings.types.SettingFolder TileCacheFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("TileCacheFolder", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, CB.WorkPath + "/repository/cache", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingFolder TileCacheFolderLocal = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("TileCacheFolderLocal", de.longri.cachebox3.settings.types.SettingCategory.Folder, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ALL, true));
    public static final de.longri.cachebox3.settings.types.SettingFolder MapPackFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("MapPackFolder", de.longri.cachebox3.settings.types.SettingCategory.Map, EXPERT, CB.WorkPath + "/repository/maps", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, false));
    public static final de.longri.cachebox3.settings.types.SettingFolder MapPackFolderLocal = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFolder("MapPackFolderLocal", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, CB.WorkPath + "/repository/maps", de.longri.cachebox3.settings.types.SettingStoreType.Local, de.longri.cachebox3.settings.types.SettingUsage.ALL, false));

    public static final de.longri.cachebox3.settings.types.SettingStringList CurrentMapLayer = (de.longri.cachebox3.settings.types.SettingStringList) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingStringList("CurrentMapLayer", de.longri.cachebox3.settings.types.SettingCategory.Map, DEVELOPER, new String[]{"Mapnik"}, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingString CurrentMapOverlayLayer = (de.longri.cachebox3.settings.types.SettingString) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingString("CurrentMapOverlayLayer", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingDouble MapInitLatitude = (de.longri.cachebox3.settings.types.SettingDouble) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingDouble("MapInitLatitude", de.longri.cachebox3.settings.types.SettingCategory.Positions, EXPERT, -1000, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL));

    public static final de.longri.cachebox3.settings.types.SettingDouble MapInitLongitude = (de.longri.cachebox3.settings.types.SettingDouble) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingDouble("MapInitLongitude", de.longri.cachebox3.settings.types.SettingCategory.Positions, EXPERT, -1000, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL));

    public static final de.longri.cachebox3.settings.types.SettingInt lastZoomLevel = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingInt("lastZoomLevel", de.longri.cachebox3.settings.types.SettingCategory.Map, DEVELOPER, 14, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL));

    public static final de.longri.cachebox3.settings.types.SettingBool MoveMapCenterWithSpeed = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("MoveMapCenterWithSpeed", de.longri.cachebox3.settings.types.SettingCategory.CarMode, NORMAL, false, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingInt MoveMapCenterMaxSpeed = (de.longri.cachebox3.settings.types.SettingInt) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingInt("MoveMapCenterMaxSpeed", de.longri.cachebox3.settings.types.SettingCategory.CarMode, NORMAL, 60, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingBool ShowAccuracyCircle = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ShowAccuracyCircle", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));
    public static final de.longri.cachebox3.settings.types.SettingBool ShowMapCenterCross = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("ShowMapCenterCross", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingBool PositionMarkerTransparent = (de.longri.cachebox3.settings.types.SettingBool) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingBool("PositionMarkerTransparent", de.longri.cachebox3.settings.types.SettingCategory.Map, EXPERT, true, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB));

    public static final de.longri.cachebox3.settings.types.SettingIntArray OsmMinLevel = (de.longri.cachebox3.settings.types.SettingIntArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingIntArray("OsmMinLevel", de.longri.cachebox3.settings.types.SettingCategory.Map, EXPERT, 7, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, Level));
    public static final de.longri.cachebox3.settings.types.SettingIntArray OsmMaxLevel = (de.longri.cachebox3.settings.types.SettingIntArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingIntArray("OsmMaxLevel", de.longri.cachebox3.settings.types.SettingCategory.Map, EXPERT, 19, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, Level));
    public static final de.longri.cachebox3.settings.types.SettingIntArray CompassMapMinZoomLevel = (de.longri.cachebox3.settings.types.SettingIntArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingIntArray("CompassMapMinZoomLevel", de.longri.cachebox3.settings.types.SettingCategory.Map, EXPERT, 13, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, Level));
    public static final de.longri.cachebox3.settings.types.SettingIntArray CompassMapMaxZommLevel = (de.longri.cachebox3.settings.types.SettingIntArray) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingIntArray("CompassMapMaxZommLevel", de.longri.cachebox3.settings.types.SettingCategory.Map, EXPERT, 20, de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, Level));

    public static final de.longri.cachebox3.settings.types.SettingFolder RenderThemesFolder = (de.longri.cachebox3.settings.types.SettingFolder) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingFolder("RenderThemesFolder", de.longri.cachebox3.settings.types.SettingCategory.Map, NORMAL, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ALL, false));
    public static final de.longri.cachebox3.settings.types.SettingFile MapsforgeDayTheme = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFile("MapsforgeDayTheme", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, "xml"));
    public static final de.longri.cachebox3.settings.types.SettingFile MapsforgeNightTheme = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFile("MapsforgeNightTheme", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, "xml"));
    public static final de.longri.cachebox3.settings.types.SettingFile MapsforgeCarDayTheme = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new de.longri.cachebox3.settings.types.SettingFile("MapsforgeCarDayTheme", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, "xml"));
    public static final de.longri.cachebox3.settings.types.SettingFile MapsforgeCarNightTheme = (de.longri.cachebox3.settings.types.SettingFile) de.longri.cachebox3.settings.types.SettingsList.addSetting(new SettingFile("MapsforgeCarNightTheme", de.longri.cachebox3.settings.types.SettingCategory.Map, NEVER, "", de.longri.cachebox3.settings.types.SettingStoreType.Global, de.longri.cachebox3.settings.types.SettingUsage.ACB, "xml"));


    public static final de.longri.cachebox3.settings.types.SettingBool DEBUG_MapGrid = (de.longri.cachebox3.settings.types.SettingBool) SettingsList.addSetting(new SettingBool("DEBUG_MapGrid", SettingCategory.Debug, NORMAL, false, SettingStoreType.Global, SettingUsage.ACB));


    //    public static final SettingEnum<Live_Cache_Time> LiveCacheTime = new SettingEnum<Live_Cache_Time>("LiveCacheTime", SettingCategory.LiveMap, NORMAL, Live_Cache_Time.h_6, SettingStoreType.Global, SettingUsage.ACB, Live_Cache_Time.h_6);
//    public static final SettingEnum<CB_Core.Api.LiveMapQue.Live_Radius> LiveRadius = new SettingEnum<CB_Core.Api.LiveMapQue.Live_Radius>("LiveRadius", SettingCategory.LiveMap, NORMAL, CB_Core.Api.LiveMapQue.Live_Radius.Zoom_14,
//            SettingStoreType.Global, SettingUsage.ACB, CB_Core.Api.LiveMapQue.Live_Radius.Zoom_14);
//    public static final SettingEnum<CB_Core.Api.LiveMapQue.Live_Radius> LiveRadius = new SettingEnum<CB_Core.Api.LiveMapQue.Live_Radius>("LiveRadius", SettingCategory.LiveMap, NORMAL, CB_Core.Api.LiveMapQue.Live_Radius.Zoom_14,
//            SettingStoreType.Global, SettingUsage.ACB, CB_Core.Api.LiveMapQue.Live_Radius.Zoom_14);
//    public static final SettingEnum<Live_Cache_Time> LiveCacheTime = new SettingEnum<Live_Cache_Time>("LiveCacheTime", SettingCategory.LiveMap, NORMAL, Live_Cache_Time.h_6, SettingStoreType.Global, SettingUsage.ACB, Live_Cache_Time.h_6);

}
