sudo: "required"

before_install:
  - chmod +x gradlew
  - sudo apt-get install openjfx

install: true
language: java

jdk: openjdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


global: GRADLE_OPTS="-Xmx2048m"
before_script:
  - mv travis_settings.gradle settings.gradle
script:
- ./gradlew junit_test:junitPlatformTest #--stacktrace --debug

